import React, { useState } from 'react';
import { motion } from 'motion/react';
import { PaperSummary, PresetPaper, TradeoffRow } from '../types';
import { PRESET_PAPERS } from '../data/presetPapers';
import {
  Scale,
  X,
  ArrowRightLeft,
  CheckCircle2,
  Copy,
  Check,
  Download,
  Sparkles,
  Layers,
  Cpu,
  Zap,
  Award
} from 'lucide-react';
import confetti from 'canvas-confetti';

interface ComparativeSynthesisModalProps {
  currentSummary?: PaperSummary | null;
  paperA?: PresetPaper;
  paperB?: PresetPaper;
  isOpen: boolean;
  onClose: () => void;
}

export const ComparativeSynthesisModal: React.FC<ComparativeSynthesisModalProps> = ({
  currentSummary,
  paperA,
  paperB,
  isOpen,
  onClose
}) => {
  const [paperAId, setPaperAId] = useState<string>(paperA?.id || 'transformer-2017');
  const [paperBId, setPaperBId] = useState<string>(paperB?.id || 'resnet-2015');
  const [copiedMarkdown, setCopiedMarkdown] = useState(false);

  if (!isOpen) return null;

  // Options list includes presets and current paper (if currentSummary exists)
  const paperOptions = [
    ...(currentSummary && currentSummary.title ? [{
      id: 'current',
      title: currentSummary.title,
      authors: Array.isArray(currentSummary.authors) ? currentSummary.authors.join(', ') : (currentSummary.authors || 'Research Team'),
      year: currentSummary.publicationYear || new Date().getFullYear(),
      summary: currentSummary
    }] : []),
    ...PRESET_PAPERS.map(p => ({
      id: p.id,
      title: p.title || 'Untitled Research',
      authors: p.authors || 'Research Team',
      year: p.year || 2024,
      summary: p.preCalculatedSummary!
    }))
  ];

  const defaultOption = paperOptions[0] || {
    id: 'default-fallback',
    title: 'Research Paper',
    authors: 'Research Authors',
    year: 2024,
    summary: PRESET_PAPERS[0].preCalculatedSummary!
  };

  const selectedA = paperOptions.find(p => p.id === paperAId) || defaultOption;
  const selectedB = paperOptions.find(p => p.id === paperBId) || paperOptions[1] || defaultOption;

  // Dynamic Trade-off Comparison Rows
  const tradeoffMatrix: TradeoffRow[] = [
    {
      dimension: 'Core Structural Primitive',
      paperAValue: selectedA?.id === 'transformer-2017' ? 'Multi-Head Self-Attention (Permutation Invariant)' : (selectedA?.summary?.keyTakeaways?.[0]?.title || 'Dense Convolution / Sequence'),
      paperBValue: selectedB?.id === 'resnet-2015' ? 'Residual Shortcut Skip Connections F(x) + x' : (selectedB?.summary?.keyTakeaways?.[0]?.title || 'Attention / Spatial'),
      advantage: 'Balanced',
      notes: 'Transformer trades inductive bias for universal sequence scaling; ResNet optimizes spatial locality.'
    },
    {
      dimension: 'Computational Complexity',
      paperAValue: selectedA?.id === 'transformer-2017' ? 'O(N^2) quadratic with sequence length N' : 'O(N) with model depth',
      paperBValue: selectedB?.id === 'resnet-2015' ? 'O(K^2 * C_in * C_out) linear with pixel count' : 'O(N^2) cross-attention',
      advantage: selectedB?.id === 'resnet-2015' ? 'B' : 'A',
      notes: 'CNNs remain significantly more cache & memory efficient for high-resolution visual inputs.'
    },
    {
      dimension: 'Training Parallelism',
      paperAValue: selectedA?.id === 'transformer-2017' ? 'Full GPU parallelization (Zero Recurrence)' : 'High parallel throughput',
      paperBValue: selectedB?.id === 'resnet-2015' ? 'Full parallelization across spatial feature maps' : 'Evoformer iterative recycling',
      advantage: 'A',
      notes: 'Self-attention allows parallel multi-GPU batching across all tokens simultaneously.'
    },
    {
      dimension: 'Maximum Verified Depth / Scale',
      paperAValue: selectedA?.id === 'transformer-2017' ? 'Trillions of parameters across 100+ transformer layers' : 'Large scale foundational weights',
      paperBValue: selectedB?.id === 'resnet-2015' ? '152 to 1001 convolutional layers without gradient degradation' : 'High depth stability',
      advantage: 'Balanced',
      notes: 'Both introduced pivotal mechanics enabling ultra-deep neural networks without vanishing gradients.'
    },
    {
      dimension: 'Data Hunger & Inductive Bias',
      paperAValue: 'Minimal inductive bias; requires massive web-scale pre-training data',
      paperBValue: 'Strong translational invariance; trains efficiently from smaller datasets',
      advantage: selectedB?.id === 'resnet-2015' ? 'B' : 'A',
      notes: 'ResNet excels in data-constrained visual scenarios; Transformers dominate massive foundation corpora.'
    }
  ];

  const handleCopyMarkdown = () => {
    const titleA = selectedA?.title || 'Paper A';
    const titleB = selectedB?.title || 'Paper B';
    const md = `# Comparative Literature Synthesis: ${titleA} vs ${titleB}
*Generated by PaperVision AI*

## Overview
Comparing **${titleA}** (${selectedA?.year || ''}) by ${selectedA?.authors || ''} against **${titleB}** (${selectedB?.year || ''}) by ${selectedB?.authors || ''}.

## Trade-off & Architectural Matrix
| Dimension | ${titleA} | ${titleB} | Advantage / Trade-off |
|---|---|---|---|
${tradeoffMatrix.map(r => `| **${r.dimension}** | ${r.paperAValue} | ${r.paperBValue} | ${r.notes} |`).join('\n')}

## Empirical Verdict
- **${titleA}** is optimal when massive pre-training data and sequence flexibility are required.
- **${titleB}** is optimal when hardware efficiency, low latency, and strong local geometric bias are paramount.
`;
    navigator.clipboard.writeText(md);
    setCopiedMarkdown(true);
    confetti({ particleCount: 25, spread: 45 });
    setTimeout(() => setCopiedMarkdown(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-6 bg-black/60 backdrop-blur-sm">
      <motion.div
        initial={{ opacity: 0, scale: 0.96 }}
        animate={{ opacity: 1, scale: 1 }}
        exit={{ opacity: 0, scale: 0.96 }}
        className="relative w-full max-w-5xl max-h-[92vh] flex flex-col bg-[#FDFCFB] rounded-2xl shadow-2xl border border-[#1A1A1A]/15 overflow-hidden"
      >
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-[#1A1A1A]/10 bg-white">
          <div className="flex items-center gap-3">
            <span className="p-2 rounded-xl bg-[#A67C52]/10 text-[#A67C52]">
              <Scale className="w-5 h-5" />
            </span>
            <div>
              <div className="flex items-center gap-2">
                <span className="editorial-badge text-[#A67C52]">Literature Review Engine</span>
                <span className="text-[11px] font-mono text-[#1A1A1A]/50">• Comparative Matrix</span>
              </div>
              <h2 className="text-xl font-serif text-[#1A1A1A]">
                Multi-Paper Comparative Synthesis
              </h2>
            </div>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="px-3 py-1.5 rounded-lg border border-[#1A1A1A]/15 text-xs font-mono text-[#1A1A1A] hover:bg-[#FAF9F5] transition-all flex items-center gap-1.5 btn-tactile"
            >
              {copiedMarkdown ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
              <span>Copy Synthesis</span>
            </button>
            <button
              onClick={onClose}
              className="p-2 rounded-lg text-[#1A1A1A]/50 hover:text-[#1A1A1A] hover:bg-black/5 transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Paper Selectors (Fragments UI) */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 p-6 bg-[#FAF9F5] border-b border-[#1A1A1A]/10">
          {/* Paper A Selector */}
          <div className="bg-white p-4 rounded-xl border border-[#1A1A1A]/10 shadow-xs">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-bold uppercase tracking-widest text-[#A67C52] bg-[#A67C52]/10 px-2 py-0.5 rounded">
                Candidate Paper A
              </span>
              <span className="text-xs font-mono text-[#1A1A1A]/50">{selectedA?.year}</span>
            </div>
            <select
              value={paperAId}
              onChange={(e) => setPaperAId(e.target.value)}
              aria-label="Select Candidate Paper A"
              className="w-full text-sm font-semibold text-[#1A1A1A] bg-transparent border-0 border-b border-[#1A1A1A]/15 pb-2 focus:ring-0 focus:border-[#A67C52] mb-2 cursor-pointer"
            >
              {paperOptions.map(p => (
                <option key={p.id} value={p.id}>
                  {p.title} ({p.year})
                </option>
              ))}
            </select>
            <p className="text-xs text-[#1A1A1A]/70 line-clamp-2 leading-relaxed">
              {selectedA?.summary?.tldr || 'Overview of paper architecture and contribution.'}
            </p>
          </div>

          {/* Paper B Selector */}
          <div className="bg-white p-4 rounded-xl border border-[#1A1A1A]/10 shadow-xs">
            <div className="flex items-center justify-between mb-2">
              <span className="text-[10px] font-bold uppercase tracking-widest text-[#1A1A1A] bg-[#1A1A1A]/10 px-2 py-0.5 rounded">
                Candidate Paper B
              </span>
              <span className="text-xs font-mono text-[#1A1A1A]/50">{selectedB?.year}</span>
            </div>
            <select
              value={paperBId}
              onChange={(e) => setPaperBId(e.target.value)}
              aria-label="Select Candidate Paper B"
              className="w-full text-sm font-semibold text-[#1A1A1A] bg-transparent border-0 border-b border-[#1A1A1A]/15 pb-2 focus:ring-0 focus:border-[#A67C52] mb-2 cursor-pointer"
            >
              {paperOptions.map(p => (
                <option key={p.id} value={p.id}>
                  {p.title} ({p.year})
                </option>
              ))}
            </select>
            <p className="text-xs text-[#1A1A1A]/70 line-clamp-2 leading-relaxed">
              {selectedB?.summary?.tldr || 'Overview of paper architecture and contribution.'}
            </p>
          </div>
        </div>

        {/* Comparison Matrix Table */}
        <div className="flex-1 overflow-y-auto p-6">
          <div className="border border-[#1A1A1A]/10 rounded-xl overflow-hidden bg-white shadow-xs mb-6">
            <div className="grid grid-cols-12 bg-[#1A1A1A] text-white text-xs font-semibold py-3 px-4 font-mono">
              <div className="col-span-3">Evaluation Axis</div>
              <div className="col-span-4 text-[#A67C52]">{(selectedA?.title || 'Paper A').slice(0, 24)}...</div>
              <div className="col-span-4">{(selectedB?.title || 'Paper B').slice(0, 24)}...</div>
              <div className="col-span-1 text-right">Edge</div>
            </div>

            <div className="divide-y divide-[#1A1A1A]/10">
              {tradeoffMatrix.map((row, idx) => (
                <div key={idx} className="grid grid-cols-12 text-xs p-4 hover:bg-[#FAF9F5] transition-colors items-center">
                  <div className="col-span-3 font-semibold text-[#1A1A1A] pr-2">
                    {row.dimension}
                  </div>
                  <div className="col-span-4 text-[#1A1A1A]/85 pr-3 leading-relaxed">
                    {row.paperAValue}
                  </div>
                  <div className="col-span-4 text-[#1A1A1A]/85 pr-3 leading-relaxed">
                    {row.paperBValue}
                  </div>
                  <div className="col-span-1 text-right">
                    <span
                      className={`inline-block text-[10px] font-bold px-2 py-0.5 rounded font-mono ${
                        row.advantage === 'A'
                          ? 'bg-[#A67C52]/15 text-[#A67C52]'
                          : row.advantage === 'B'
                          ? 'bg-blue-100 text-blue-800'
                          : 'bg-gray-100 text-gray-700'
                      }`}
                    >
                      {row.advantage === 'A' ? 'Paper A' : row.advantage === 'B' ? 'Paper B' : 'Tie'}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Synthesis Verdict Callout */}
          <div className="p-5 rounded-xl bg-[#F5F2EA] border border-[#A67C52]/30 flex items-start gap-3">
            <span className="p-2 rounded-lg bg-[#A67C52] text-white mt-0.5">
              <Award className="w-5 h-5" />
            </span>
            <div>
              <h4 className="text-sm font-bold text-[#1A1A1A] mb-1">
                Comparative Synthesis Verdict
              </h4>
              <p className="text-xs text-[#1A1A1A]/80 leading-relaxed">
                When scaling across massive multi-modal corpora or text reasoning pipelines, <strong>{selectedA?.title || 'Paper A'}</strong> delivers superior expressivity and parallel throughput. Conversely, for latency-critical edge deployments, rigid spatial invariance, or constrained compute budgets, <strong>{selectedB?.title || 'Paper B'}</strong> remains the gold-standard architectural backbone.
              </p>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};
