import fs from 'node:fs';
function change(file,from,to){let s=fs.readFileSync(file,'utf8');if(!s.includes(from))throw new Error('Missing edit target in '+file+': '+from.slice(0,90));fs.writeFileSync(file,s.replace(from,to));}
change('worker/index.ts',"if(p==='/api/auth/logout'){","if(p==='/api/auth/logout'&&req.method==='POST'){");
change('worker/index.ts','for(let i=1;i<=meta.revision;i++)await env.FILES.delete(`notebooks/${u.id}/${match[1]}/${i}.json`);','let cursor;do{const listed=await env.FILES.list({prefix:`notebooks/${u.id}/${match[1]}/`,cursor});if(listed.objects.length)await env.FILES.delete(listed.objects.map((o:any)=>o.key));cursor=listed.truncated?listed.cursor:undefined;}while(cursor);');
change('worker/index.ts',"if(p==='/api/notebooks'&&req.method==='POST'){const b=await body(req);","if(p==='/api/notebooks'&&req.method==='POST'){await limit(env,`notebooks:${u.id}:${now().slice(0,10)}`,20);const b=await body(req);");
change('worker/index.ts',"const b=await body(req);if(!Array.isArray(b.sources)","const b=await body(req);await limit(env,`saves:${u.id}:${now().slice(0,13)}`,300);if(!Array.isArray(b.sources)");
change('worker/index.ts',"throw new HttpError(400,'Invalid notebook data.');return json", "throw new HttpError(400,'Invalid notebook data.');for(const s of b.sources){if(typeof s.id!=='string'||typeof s.text!=='string'||s.text.length>600000||typeof s.title!=='string')throw new HttpError(400,'Invalid source data.');}if(!Array.isArray(b.selected)||!Array.isArray(b.notes)||!Array.isArray(b.tags))throw new HttpError(400,'Invalid notebook data.');return json");
change('src/v2/App.tsx',"import React,{useEffect,useRef,useState} from 'react';","import React,{createContext,useContext,lazy,Suspense,useEffect,useRef,useState} from 'react';\nimport ReactMarkdown from 'react-markdown';\nimport remarkGfm from 'remark-gfm';\nconst Charts=lazy(()=>import('./Charts'));\nconst UiContext=createContext({error:'',busy:'',toast:''});\nfunction Markdown({text}:{text:string}){return <ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({href,children})=><a href={href} target=\"_blank\" rel=\"noreferrer\">{children}</a>}}>{text}</ReactMarkdown>;}");
change('src/v2/App.tsx','}){const ref=useRef<HTMLDialogElement>(null);','}){const ui=useContext(UiContext);const ref=useRef<HTMLDialogElement>(null);');
change('src/v2/App.tsx','</div>{children}</dialog>;}', '</div>{ui.error&&<p className="modal-error" role="alert">{ui.error}</p>}{ui.busy&&<p className="modal-progress" role="status">{ui.busy}…</p>}{ui.toast&&<p className="modal-progress" role="status">{ui.toast}</p>}{children}</dialog>;}');
change('src/v2/App.tsx','return <><header className="topbar">','return <UiContext.Provider value={{error,busy,toast}}><header className="topbar">');
change('src/v2/App.tsx',' </>;\n}', ' </UiContext.Provider>;\n}');
change('src/v2/App.tsx','setPresent(true);setSlideIndex(0);','setModal(\'\');setPresent(true);setSlideIndex(0);');
change('src/v2/App.tsx','<p>{m.text}</p>','<div className="markdown"><Markdown text={m.text}/></div>');
change('src/v2/App.tsx','<div className="tool-result">{toolText}</div>','<div className="tool-result markdown"><Markdown text={toolText}/></div>');
change('src/v2/App.tsx','<h2>Reported numbers</h2>','<h2>Reported numbers</h2>');
change('src/v2/App.tsx','<section className="finding-section"><h2>Explore the concepts</h2>','{!!n.summary.metrics.length&&<Suspense fallback={<p>Loading chart…</p>}><Charts metrics={n.summary.metrics}/></Suspense>}<section className="finding-section"><h2>Explore the concepts</h2>');
